# Generated by Django 6.0.3 on 2026-03-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_movie_is_active_remove_seat_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rows',
            field=models.CharField(max_length=2),
        ),
    ]
