# Generated by Django 6.0.3 on 2026-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_title_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rows',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(),
        ),
    ]
